### ISSUE TITLE
Fix crash when closing a JetBrains window

### ISSUE THREAD

**Issue by dalyIsaac** [dalyIsaac/Whim#402]
This occurred when opening IntelliJ from Gateway. A dialog would open while the connection was loading. Once the dialog disappeared, the following error occurred:

```log
2023-06-07 12:51:59.199 +10:00 [DBG] WindowManager:260              [AddWindow]                    Adding window 1837010
2023-06-07 12:51:59.202 +10:00 [DBG] WindowManager:260              [AddWindow]                    Adding window 1837010
2023-06-07 12:51:59.232 +10:00 [DBG] WindowManager:260              [AddWindow]                    Adding window 1837010
2023-06-07 12:51:59.233 +10:00 [DBG] WindowManager:111              [CreateWindow]                 Adding window 1837010
2023-06-07 12:51:59.235 +10:00 [DBG] WindowManager:296              [AddWindow]                    Added  (jetbrains_client64) [7668] <SunAwtFrame> {1837010}
2023-06-07 12:51:59.235 +10:00 [DBG] WindowManager:304              [OnWindowAdded]                Window added:  (jetbrains_client64) [7668] <SunAwtFrame> {1837010}
2023-06-07 12:51:59.235 +10:00 [DBG] WorkspaceManager:337           [WindowAdded]                  Adding window  (jetbrains_client64) [7668] <SunAwtFrame> {1837010}
2023-06-07 12:51:59.235 +10:00 [DBG] RouterManager:122              [RouteWindow]                  Routing window  (jetbrains_client64) [7668] <SunAwtFrame> {1837010}
2023-06-07 12:51:59.236 +10:00 [DBG] RouterManager:133              [RouteWindow]                  Window  (jetbrains_client64) [7668] <SunAwtFrame> {1837010} not routed
2023-06-07 12:51:59.236 +10:00 [DBG] MonitorManager:216             [GetMonitorAtPoint]            Getting monitor at point (1920, 1087)
2023-06-07 12:51:59.236 +10:00 [DBG] Workspace:197                  [AddWindow]                    Adding window  (jetbrains_client64) [7668] <SunAwtFrame> {1837010} to workspace Chat
2023-06-07 12:51:59.236 +10:00 [DBG] TreeLayoutEngine:59            [AddWindow]                    Adding window  (jetbrains_client64) [7668] <SunAwtFrame> {1837010} to layout engine Tree
2023-06-07 12:51:59.236 +10:00 [DBG] TreeLayoutEngine:492           [GetAdjacentNode]              Getting node in direction Right for window JetBrains Client (jetbrains_client64) [7668] <SunAwtDialog> {526298}
2023-06-07 12:51:59.237 +10:00 [DBG] SplitNode:120                  [Add]                          Adding  (jetbrains_client64) [7668] <SunAwtFrame> {1837010} to Whim.TreeLayout.SplitNode, in direction Right
2023-06-07 12:51:59.237 +10:00 [DBG] BaseStackLayoutEngine:34       [Add]                          Adding window  (jetbrains_client64) [7668] <SunAwtFrame> {1837010} to layout engine Column
2023-06-07 12:51:59.237 +10:00 [DBG] BaseStackLayoutEngine:34       [Add]                          Adding window  (jetbrains_client64) [7668] <SunAwtFrame> {1837010} to layout engine Right to left
2023-06-07 12:51:59.237 +10:00 [DBG] Workspace:377                  [DoLayout]                     Workspace Chat
2023-06-07 12:51:59.237 +10:00 [DBG] WorkspaceManager:302           [GetMonitorForWorkspace]       Getting monitor for active workspace Chat
2023-06-07 12:51:59.237 +10:00 [DBG] WorkspaceManager:309           [GetMonitorForWorkspace]       Found monitor Monitor[Bounds=(X: -1920, Y: 0, Width: 7200, Height: 2910) WorkingArea=(X: 0, Y: 0, Width: 3840, Height: 2120) Name=DISPLAY ScaleFactor=100 IsPrimary=True] for workspace Chat
2023-06-07 12:51:59.237 +10:00 [DBG] FocusIndicatorPlugin:136       [Hide]                         Hiding focus indicator
2023-06-07 12:51:59.237 +10:00 [DBG] NativeManager:45               [HideWindow]                   Hiding window HWND 918852
2023-06-07 12:51:59.244 +10:00 [DBG] NativeManager:73               [ShowWindowNoActivate]         Showing window HWND 263324 no activate
2023-06-07 12:51:59.245 +10:00 [DBG] NativeManager:73               [ShowWindowNoActivate]         Showing window HWND 4327262 no activate
2023-06-07 12:51:59.246 +10:00 [DBG] NativeManager:73               [ShowWindowNoActivate]         Showing window HWND 526298 no activate
2023-06-07 12:51:59.246 +10:00 [DBG] NativeManager:73               [ShowWindowNoActivate]         Showing window HWND 1837010 no activate
2023-06-07 12:51:59.247 +10:00 [DBG] NativeManager:73               [ShowWindowNoActivate]         Showing window HWND 329584 no activate
2023-06-07 12:51:59.302 +10:00 [DBG] FocusIndicatorPlugin:100       [Show]                         Showing focus indicator
2023-06-07 12:51:59.303 +10:00 [DBG] NativeManager:73               [ShowWindowNoActivate]         Showing window HWND 918852 no activate
2023-06-07 12:51:59.311 +10:00 [DBG] Window:87                      [Focus]                         (jetbrains_client64) [7668] <SunAwtFrame> {1837010}
2023-06-07 12:51:59.311 +10:00 [DBG] WindowManager:317              [OnWindowFocused]              Window focused:  (jetbrains_client64) [7668] <SunAwtFrame> {1837010}
2023-06-07 12:51:59.311 +10:00 [DBG] MonitorManager:84              [WindowFocused]                Focusing on  (jetbrains_client64) [7668] <SunAwtFrame> {1837010}
2023-06-07 12:51:59.311 +10:00 [DBG] WorkspaceManager:302           [GetMonitorForWorkspace]       Getting monitor for active workspace Chat
2023-06-07 12:51:59.311 +10:00 [DBG] WorkspaceManager:309           [GetMonitorForWorkspace]       Found monitor Monitor[Bounds=(X: -1920, Y: 0, Width: 7200, Height: 2910) WorkingArea=(X: 0, Y: 0, Width: 3840, Height: 2120) Name=DISPLAY ScaleFactor=100 IsPrimary=True] for workspace Chat
2023-06-07 12:51:59.311 +10:00 [DBG] WorkspaceManager:381           [WindowFocused]                Window focused:  (jetbrains_client64) [7668] <SunAwtFrame> {1837010}
2023-06-07 12:51:59.311 +10:00 [DBG] Workspace:118                  [WindowFocused]                Focused window  (jetbrains_client64) [7668] <SunAwtFrame> {1837010} in workspace Chat
2023-06-07 12:51:59.311 +10:00 [DBG] WorkspaceManager:302           [GetMonitorForWorkspace]       Getting monitor for active workspace Chat
2023-06-07 12:51:59.311 +10:00 [DBG] WorkspaceManager:309           [GetMonitorForWorkspace]       Found monitor Monitor[Bounds=(X: -1920, Y: 0, Width: 7200, Height: 2910) WorkingArea=(X: 0, Y: 0, Width: 3840, Height: 2120) Name=DISPLAY ScaleFactor=100 IsPrimary=True] for workspace Chat
2023-06-07 12:51:59.311 +10:00 [DBG] FocusIndicatorPlugin:100       [Show]                         Showing focus indicator
2023-06-07 12:51:59.312 +10:00 [DBG] NativeManager:73               [ShowWindowNoActivate]         Showing window HWND 918852 no activate
2023-06-07 12:51:59.313 +10:00 [DBG] WorkspaceManager:302           [GetMonitorForWorkspace]       Getting monitor for active workspace Chat
2023-06-07 12:51:59.313 +10:00 [DBG] WorkspaceManager:309           [GetMonitorForWorkspace]       Found monitor Monitor[Bounds=(X: -1920, Y: 0, Width: 7200, Height: 2910) WorkingArea=(X: 0, Y: 0, Width: 3840, Height: 2120) Name=DISPLAY ScaleFactor=100 IsPrimary=True] for workspace Chat
2023-06-07 12:51:59.313 +10:00 [DBG] WorkspaceManager:302           [GetMonitorForWorkspace]       Getting monitor for active workspace Chat
2023-06-07 12:51:59.313 +10:00 [DBG] WorkspaceManager:309           [GetMonitorForWorkspace]       Found monitor Monitor[Bounds=(X: -1920, Y: 0, Width: 7200, Height: 2910) WorkingArea=(X: 0, Y: 0, Width: 3840, Height: 2120) Name=DISPLAY ScaleFactor=100 IsPrimary=True] for workspace Chat
```

Second repro:

```
2023-06-07 13:11:37.329 +10:00 [DBG] WindowManager:260              [AddWindow]                    Adding window 1312494
2023-06-07 13:11:37.334 +10:00 [DBG] WindowManager:260              [AddWindow]                    Adding window 1312494
2023-06-07 13:11:37.388 +10:00 [DBG] WindowManager:260              [AddWindow]                    Adding window 1312494
2023-06-07 13:11:37.388 +10:00 [DBG] WindowManager:111              [CreateWindow]                 Adding window 1312494
2023-06-07 13:11:37.390 +10:00 [DBG] WindowManager:296              [AddWindow]                    Added  (jetbrains_client64) [10660] <SunAwtFrame> {1312494}
2023-06-07 13:11:37.390 +10:00 [DBG] WindowManager:304              [OnWindowAdded]                Window added:  (jetbrains_client64) [10660] <SunAwtFrame> {1312494}
2023-06-07 13:11:37.390 +10:00 [DBG] WorkspaceManager:337           [WindowAdded]                  Adding window  (jetbrains_client64) [10660] <SunAwtFrame> {1312494}
2023-06-07 13:11:37.391 +10:00 [DBG] RouterManager:122              [RouteWindow]                  Routing window  (jetbrains_client64) [10660] <SunAwtFrame> {1312494}
2023-06-07 13:11:37.391 +10:00 [DBG] RouterManager:133              [RouteWindow]                  Window  (jetbrains_client64) [10660] <SunAwtFrame> {1312494} not routed
2023-06-07 13:11:37.391 +10:00 [DBG] MonitorManager:216             [GetMonitorAtPoint]            Getting monitor at point (640, 1087)
2023-06-07 13:11:37.391 +10:00 [DBG] Workspace:197                  [AddWindow]                    Adding window  (jetbrains_client64) [10660] <SunAwtFrame> {1312494} to workspace Chat
2023-06-07 13:11:37.391 +10:00 [DBG] TreeLayoutEngine:59            [AddWindow]                    Adding window  (jetbrains_client64) [10660] <SunAwtFrame> {1312494} to layout engine Tree
2023-06-07 13:11:37.391 +10:00 [DBG] TreeLayoutEngine:492           [GetAdjacentNode]              Getting node in direction Right for window JetBrains Client (jetbrains_client64) [10660] <SunAwtDialog> {1443958}
2023-06-07 13:11:37.391 +10:00 [DBG] SplitNode:120                  [Add]                          Adding  (jetbrains_client64) [10660] <SunAwtFrame> {1312494} to Whim.TreeLayout.SplitNode, in direction Right
2023-06-07 13:11:37.392 +10:00 [DBG] BaseStackLayoutEngine:34       [Add]                          Adding window  (jetbrains_client64) [10660] <SunAwtFrame> {1312494} to layout engine Column
2023-06-07 13:11:37.392 +10:00 [DBG] BaseStackLayoutEngine:34       [Add]                          Adding window  (jetbrains_client64) [10660] <SunAwtFrame> {1312494} to layout engine Right to left
2023-06-07 13:11:37.392 +10:00 [DBG] Workspace:377                  [DoLayout]                     Workspace Chat
2023-06-07 13:11:37.392 +10:00 [DBG] WorkspaceManager:302           [GetMonitorForWorkspace]       Getting monitor for active workspace Chat
2023-06-07 13:11:37.392 +10:00 [DBG] WorkspaceManager:309           [GetMonitorForWorkspace]       Found monitor Monitor[Bounds=(X: -1920, Y: 0, Width: 7200, Height: 2910) WorkingArea=(X: 0, Y: 0, Width: 3840, Height: 2120) Name=DISPLAY ScaleFactor=100 IsPrimary=True] for workspace Chat
2023-06-07 13:11:37.392 +10:00 [DBG] FocusIndicatorPlugin:136       [Hide]                         Hiding focus indicator
2023-06-07 13:11:37.392 +10:00 [DBG] NativeManager:45               [HideWindow]                   Hiding window HWND 1181434
2023-06-07 13:11:37.397 +10:00 [DBG] NativeManager:73               [ShowWindowNoActivate]         Showing window HWND 263324 no activate
2023-06-07 13:11:37.397 +10:00 [DBG] NativeManager:73               [ShowWindowNoActivate]         Showing window HWND 329584 no activate
2023-06-07 13:11:37.398 +10:00 [DBG] NativeManager:73               [ShowWindowNoActivate]         Showing window HWND 1968096 no activate
2023-06-07 13:11:37.399 +10:00 [DBG] NativeManager:73               [ShowWindowNoActivate]         Showing window HWND 1443958 no activate
2023-06-07 13:11:37.399 +10:00 [DBG] NativeManager:73               [ShowWindowNoActivate]         Showing window HWND 1312494 no activate
2023-06-07 13:11:37.469 +10:00 [DBG] FocusIndicatorPlugin:100       [Show]                         Showing focus indicator
2023-06-07 13:11:37.470 +10:00 [DBG] NativeManager:73               [ShowWindowNoActivate]         Showing window HWND 1181434 no activate
2023-06-07 13:11:37.483 +10:00 [DBG] Window:87                      [Focus]                         (jetbrains_client64) [10660] <SunAwtFrame> {1312494}
2023-06-07 13:11:37.483 +10:00 [DBG] WindowManager:317              [OnWindowFocused]              Window focused:  (jetbrains_client64) [10660] <SunAwtFrame> {1312494}
2023-06-07 13:11:37.483 +10:00 [DBG] MonitorManager:84              [WindowFocused]                Focusing on  (jetbrains_client64) [10660] <SunAwtFrame> {1312494}
2023-06-07 13:11:37.483 +10:00 [DBG] WorkspaceManager:302           [GetMonitorForWorkspace]       Getting monitor for active workspace Chat
2023-06-07 13:11:37.483 +10:00 [DBG] WorkspaceManager:309           [GetMonitorForWorkspace]       Found monitor Monitor[Bounds=(X: -1920, Y: 0, Width: 7200, Height: 2910) WorkingArea=(X: 0, Y: 0, Width: 3840, Height: 2120) Name=DISPLAY ScaleFactor=100 IsPrimary=True] for workspace Chat
2023-06-07 13:11:37.483 +10:00 [DBG] WorkspaceManager:381           [WindowFocused]                Window focused:  (jetbrains_client64) [10660] <SunAwtFrame> {1312494}
2023-06-07 13:11:37.483 +10:00 [DBG] Workspace:118                  [WindowFocused]                Focused window  (jetbrains_client64) [10660] <SunAwtFrame> {1312494} in workspace Chat
2023-06-07 13:11:37.483 +10:00 [DBG] WorkspaceManager:302           [GetMonitorForWorkspace]       Getting monitor for active workspace Chat
2023-06-07 13:11:37.483 +10:00 [DBG] WorkspaceManager:309           [GetMonitorForWorkspace]       Found monitor Monitor[Bounds=(X: -1920, Y: 0, Width: 7200, Height: 2910) WorkingArea=(X: 0, Y: 0, Width: 3840, Height: 2120) Name=DISPLAY ScaleFactor=100 IsPrimary=True] for workspace Chat
2023-06-07 13:11:37.483 +10:00 [DBG] FocusIndicatorPlugin:100       [Show]                         Showing focus indicator
2023-06-07 13:11:37.484 +10:00 [DBG] NativeManager:73               [ShowWindowNoActivate]         Showing window HWND 1181434 no activate
2023-06-07 13:11:37.485 +10:00 [DBG] WorkspaceManager:302           [GetMonitorForWorkspace]       Getting monitor for active workspace Chat
2023-06-07 13:11:37.485 +10:00 [DBG] WorkspaceManager:309           [GetMonitorForWorkspace]       Found monitor Monitor[Bounds=(X: -1920, Y: 0, Width: 7200, Height: 2910) WorkingArea=(X: 0, Y: 0, Width: 3840, Height: 2120) Name=DISPLAY ScaleFactor=100 IsPrimary=True] for workspace Chat
2023-06-07 13:11:37.485 +10:00 [DBG] WorkspaceManager:302           [GetMonitorForWorkspace]       Getting monitor for active workspace Chat
2023-06-07 13:11:37.485 +10:00 [DBG] WorkspaceManager:309           [GetMonitorForWorkspace]       Found monitor Monitor[Bounds=(X: -1920, Y: 0, Width: 7200, Height: 2910) WorkingArea=(X: 0, Y: 0, Width: 3840, Height: 2120) Name=DISPLAY ScaleFactor=100 IsPrimary=True] for workspace Chat
```

```log
2023-06-12 10:06:21.086 +10:00 [DBG] WindowManager:260              [AddWindow]                    Adding window 199482
2023-06-12 10:06:21.090 +10:00 [DBG] WindowManager:260              [AddWindow]                    Adding window 199482
2023-06-12 10:06:21.119 +10:00 [DBG] WindowManager:260              [AddWindow]                    Adding window 199482
2023-06-12 10:06:21.120 +10:00 [DBG] WindowManager:111              [CreateWindow]                 Adding window 199482
2023-06-12 10:06:21.123 +10:00 [DBG] WindowManager:296              [AddWindow]                    Added  (jetbrains_client64) [13720] <SunAwtFrame> {199482}
2023-06-12 10:06:21.123 +10:00 [DBG] WindowManager:304              [OnWindowAdded]                Window added:  (jetbrains_client64) [13720] <SunAwtFrame> {199482}
2023-06-12 10:06:21.124 +10:00 [DBG] WorkspaceManager:337           [WindowAdded]                  Adding window  (jetbrains_client64) [13720] <SunAwtFrame> {199482}
2023-06-12 10:06:21.124 +10:00 [DBG] RouterManager:122              [RouteWindow]                  Routing window  (jetbrains_client64) [13720] <SunAwtFrame> {199482}
2023-06-12 10:06:21.124 +10:00 [DBG] RouterManager:133              [RouteWindow]                  Window  (jetbrains_client64) [13720] <SunAwtFrame> {199482} not routed
2023-06-12 10:06:21.124 +10:00 [DBG] MonitorManager:216             [GetMonitorAtPoint]            Getting monitor at point (1440, 1087)
2023-06-12 10:06:21.124 +10:00 [DBG] Workspace:231                  [AddWindow]                    Adding window  (jetbrains_client64) [13720] <SunAwtFrame> {199482} to workspace GSPS
2023-06-12 10:06:21.125 +10:00 [DBG] TreeLayoutEngine:59            [AddWindow]                    Adding window  (jetbrains_client64) [13720] <SunAwtFrame> {199482} to layout engine Tree
2023-06-12 10:06:21.125 +10:00 [DBG] TreeLayoutEngine:492           [GetAdjacentNode]              Getting node in direction Right for window JetBrains Client (jetbrains_client64) [13720] <SunAwtDialog> {1968018}
2023-06-12 10:06:21.126 +10:00 [DBG] SplitNode:120                  [Add]                          Adding  (jetbrains_client64) [13720] <SunAwtFrame> {199482} to Whim.TreeLayout.SplitNode, in direction Right
2023-06-12 10:06:21.126 +10:00 [DBG] BaseStackLayoutEngine:34       [Add]                          Adding window  (jetbrains_client64) [13720] <SunAwtFrame> {199482} to layout engine Column
2023-06-12 10:06:21.126 +10:00 [DBG] BaseStackLayoutEngine:34       [Add]                          Adding window  (jetbrains_client64) [13720] <SunAwtFrame> {199482} to layout engine Right to left
2023-06-12 10:06:21.126 +10:00 [DBG] Workspace:452                  [DoLayout]                     Workspace GSPS
2023-06-12 10:06:21.126 +10:00 [DBG] WorkspaceManager:302           [GetMonitorForWorkspace]       Getting monitor for active workspace GSPS
2023-06-12 10:06:21.126 +10:00 [DBG] WorkspaceManager:309           [GetMonitorForWorkspace]       Found monitor Monitor[Bounds=(X: -1920, Y: 0, Width: 7200, Height: 2910) WorkingArea=(X: 0, Y: 0, Width: 3840, Height: 2120) Name=DISPLAY ScaleFactor=100 IsPrimary=True] for workspace GSPS
2023-06-12 10:06:21.126 +10:00 [DBG] FocusIndicatorPlugin:136       [Hide]                         Hiding focus indicator
2023-06-12 10:06:21.126 +10:00 [DBG] NativeManager:45               [HideWindow]                   Hiding window HWND 265106
2023-06-12 10:06:21.130 +10:00 [DBG] WindowDeferPosHandle:41        [.ctor]                        Creating new WindowDeferPosHandle
2023-06-12 10:06:21.131 +10:00 [DBG] WindowDeferPosHandle:60        [DeferWindowPos]               Adding window Whim.WindowState after  with flags 
2023-06-12 10:06:21.131 +10:00 [DBG] WindowDeferPosHandle:60        [DeferWindowPos]               Adding window Whim.WindowState after  with flags 
2023-06-12 10:06:21.131 +10:00 [DBG] WindowDeferPosHandle:60        [DeferWindowPos]               Adding window Whim.WindowState after  with flags 
2023-06-12 10:06:21.131 +10:00 [DBG] WindowDeferPosHandle:72        [Dispose]                      Disposing WindowDeferPosHandle
2023-06-12 10:06:21.131 +10:00 [DBG] WindowDeferPosHandle:86        [Dispose]                      Setting window position 1 times
2023-06-12 10:06:21.131 +10:00 [DBG] WindowDeferPosHandle:121       [.ctor]                        Creating new InternalWindowDeferPosHandle
2023-06-12 10:06:21.132 +10:00 [DBG] WindowDeferPosHandle:175       [Dispose]                      Disposing InternalWindowDeferPosHandle
2023-06-12 10:06:21.132 +10:00 [DBG] NativeManager:73               [ShowWindowNoActivate]         Showing window HWND 1706150 no activate
2023-06-12 10:06:21.134 +10:00 [DBG] NativeManager:73               [ShowWindowNoActivate]         Showing window HWND 1968018 no activate
2023-06-12 10:06:21.134 +10:00 [DBG] NativeManager:73               [ShowWindowNoActivate]         Showing window HWND 199482 no activate
2023-06-12 10:06:21.179 +10:00 [DBG] WindowDeferPosHandle:198       [Dispose]                      Disposed InternalWindowDeferPosHandle
2023-06-12 10:06:21.179 +10:00 [DBG] WindowDeferPosHandle:99        [Dispose]                      Finished setting window position
2023-06-12 10:06:21.179 +10:00 [DBG] FocusIndicatorPlugin:100       [Show]                         Showing focus indicator
2023-06-12 10:06:21.179 +10:00 [DBG] FocusIndicatorWindow.xaml:32   [Activate]                     Activating focus indicator window
2023-06-12 10:06:21.180 +10:00 [DBG] WindowDeferPosHandle:41        [.ctor]                        Creating new WindowDeferPosHandle
2023-06-12 10:06:21.180 +10:00 [DBG] WindowDeferPosHandle:60        [DeferWindowPos]               Adding window Whim.WindowState after 1968018 with flags SWP_NOREDRAW, SWP_NOACTIVATE
2023-06-12 10:06:21.180 +10:00 [DBG] WindowDeferPosHandle:72        [Dispose]                      Disposing WindowDeferPosHandle
2023-06-12 10:06:21.180 +10:00 [DBG] WindowDeferPosHandle:86        [Dispose]                      Setting window position 1 times
2023-06-12 10:06:21.180 +10:00 [DBG] WindowDeferPosHandle:121       [.ctor]                        Creating new InternalWindowDeferPosHandle
2023-06-12 10:06:21.180 +10:00 [DBG] WindowDeferPosHandle:175       [Dispose]                      Disposing InternalWindowDeferPosHandle
2023-06-12 10:06:21.180 +10:00 [DBG] NativeManager:73               [ShowWindowNoActivate]         Showing window HWND 265106 no activate
2023-06-12 10:06:21.194 +10:00 [DBG] WindowDeferPosHandle:198       [Dispose]                      Disposed InternalWindowDeferPosHandle
2023-06-12 10:06:21.194 +10:00 [DBG] WindowDeferPosHandle:99        [Dispose]                      Finished setting window position
2023-06-12 10:06:21.194 +10:00 [DBG] Window:86                      [Focus]                         (jetbrains_client64) [13720] <SunAwtFrame> {199482}
2023-06-12 10:06:21.194 +10:00 [DBG] WindowManager:317              [OnWindowFocused]              Window focused:  (jetbrains_client64) [13720] <SunAwtFrame> {199482}
2023-06-12 10:06:21.194 +10:00 [DBG] MonitorManager:84              [WindowFocused]                Focusing on  (jetbrains_client64) [13720] <SunAwtFrame> {199482}
2023-06-12 10:06:21.194 +10:00 [DBG] WorkspaceManager:302           [GetMonitorForWorkspace]       Getting monitor for active workspace GSPS
2023-06-12 10:06:21.194 +10:00 [DBG] WorkspaceManager:309           [GetMonitorForWorkspace]       Found monitor Monitor[Bounds=(X: -1920, Y: 0, Width: 7200, Height: 2910) WorkingArea=(X: 0, Y: 0, Width: 3840, Height: 2120) Name=DISPLAY ScaleFactor=100 IsPrimary=True] for workspace GSPS
2023-06-12 10:06:21.194 +10:00 [DBG] WorkspaceManager:381           [WindowFocused]                Window focused:  (jetbrains_client64) [13720] <SunAwtFrame> {199482}
2023-06-12 10:06:21.194 +10:00 [DBG] Workspace:121                  [WindowFocused]                Focused window  (jetbrains_client64) [13720] <SunAwtFrame> {199482} in workspace GSPS
2023-06-12 10:06:21.195 +10:00 [DBG] WorkspaceManager:302           [GetMonitorForWorkspace]       Getting monitor for active workspace GSPS
2023-06-12 10:06:21.195 +10:00 [DBG] WorkspaceManager:309           [GetMonitorForWorkspace]       Found monitor Monitor[Bounds=(X: -1920, Y: 0, Width: 7200, Height: 2910) WorkingArea=(X: 0, Y: 0, Width: 3840, Height: 2120) Name=DISPLAY ScaleFactor=100 IsPrimary=True] for workspace GSPS
2023-06-12 10:06:21.195 +10:00 [DBG] FocusIndicatorPlugin:100       [Show]                         Showing focus indicator
2023-06-12 10:06:21.195 +10:00 [DBG] FocusIndicatorWindow.xaml:32   [Activate]                     Activating focus indicator window
2023-06-12 10:06:21.196 +10:00 [DBG] WindowDeferPosHandle:41        [.ctor]                        Creating new WindowDeferPosHandle
2023-06-12 10:06:21.196 +10:00 [DBG] WindowDeferPosHandle:60        [DeferWindowPos]               Adding window Whim.WindowState after 199482 with flags SWP_NOREDRAW, SWP_NOACTIVATE
2023-06-12 10:06:21.196 +10:00 [DBG] WindowDeferPosHandle:72        [Dispose]                      Disposing WindowDeferPosHandle
2023-06-12 10:06:21.196 +10:00 [DBG] WindowDeferPosHandle:86        [Dispose]                      Setting window position 1 times
2023-06-12 10:06:21.196 +10:00 [DBG] WindowDeferPosHandle:121       [.ctor]                        Creating new InternalWindowDeferPosHandle
2023-06-12 10:06:21.196 +10:00 [DBG] WindowDeferPosHandle:175       [Dispose]                      Disposing InternalWindowDeferPosHandle
2023-06-12 10:06:21.196 +10:00 [DBG] NativeManager:73               [ShowWindowNoActivate]         Showing window HWND 265106 no activate
2023-06-12 10:06:21.200 +10:00 [DBG] WindowDeferPosHandle:198       [Dispose]                      Disposed InternalWindowDeferPosHandle
2023-06-12 10:06:21.200 +10:00 [DBG] WindowDeferPosHandle:99        [Dispose]                      Finished setting window position
2023-06-12 10:06:21.200 +10:00 [DBG] WorkspaceManager:302           [GetMonitorForWorkspace]       Getting monitor for active workspace GSPS
2023-06-12 10:06:21.200 +10:00 [DBG] WorkspaceManager:309           [GetMonitorForWorkspace]       Found monitor Monitor[Bounds=(X: -1920, Y: 0, Width: 7200, Height: 2910) WorkingArea=(X: 0, Y: 0, Width: 3840, Height: 2120) Name=DISPLAY ScaleFactor=100 IsPrimary=True] for workspace GSPS
2023-06-12 10:06:21.200 +10:00 [DBG] WorkspaceManager:302           [GetMonitorForWorkspace]       Getting monitor for active workspace GSPS
2023-06-12 10:06:21.200 +10:00 [DBG] WorkspaceManager:309           [GetMonitorForWorkspace]       Found monitor Monitor[Bounds=(X: -1920, Y: 0, Width: 7200, Height: 2910) WorkingArea=(X: 0, Y: 0, Width: 3840, Height: 2120) Name=DISPLAY ScaleFactor=100 IsPrimary=True] for workspace GSPS
```

The culprit is this window:

![Image](https://user-images.githubusercontent.com/17995621/243898685-dd8c0c13-c484-4160-a725-cb5cea67feac.png)

**Comment by dalyIsaac** [comment]
Windows event logger identified the issue:

```log
Application: Whim.Runner.exe
CoreCLR Version: 7.0.22.51805
.NET Version: 7.0.0
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Whim.Bar.FocusedWindowWidget.GetShortTitle(IWindow window) in C:\Users\dalyisaac\Repos\Whim\src\Whim.Bar\FocusedWindow\FocusedWindowWidget.xaml.cs:line 51
   at Whim.Bar.FocusedWindowWidgetViewModel.WindowManager_WindowFocused(Object sender, WindowEventArgs e) in C:\Users\dalyisaac\Repos\Whim\src\Whim.Bar\FocusedWindow\FocusedWindowWidgetViewModel.cs:line 86
   at Whim.WindowManager.OnWindowFocused(IWindow window) in C:\Users\dalyisaac\Repos\Whim\src\Whim\Window\WindowManager.cs:line 320
   at Whim.Window.Focus() in C:\Users\dalyisaac\Repos\Whim\src\Whim\Window\Window.cs:line 95
   at Whim.Workspace.AddWindow(IWindow window) in C:\Users\dalyisaac\Repos\Whim\src\Whim\Workspace\Workspace.cs:line 251
   at Whim.WorkspaceManager.WindowAdded(IWindow window) in C:\Users\dalyisaac\Repos\Whim\src\Whim\Workspace\WorkspaceManager.cs:line 351
   at Whim.WindowManager.OnWindowAdded(IWindow window) in C:\Users\dalyisaac\Repos\Whim\src\Whim\Window\WindowManager.cs:line 305
   at Whim.WindowManager.AddWindow(HWND hwnd) in C:\Users\dalyisaac\Repos\Whim\src\Whim\Window\WindowManager.cs:line 292
   at Whim.WindowManager.WindowsEventHook(HWINEVENTHOOK hWinEventHook, UInt32 eventType, HWND hwnd, Int32 idObject, Int32 idChild, UInt32 idEventThread, UInt32 dwmsEventTime) in C:\Users\dalyisaac\Repos\Whim\src\Whim\Window\WindowManager.cs:line 198
```
