### ISSUE TITLE
Startup error when restarting Whim when `FocusLayout` is active

### ISSUE THREAD

**Issue by urob** [dalyIsaac/Whim#775]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Behavior

When restarting Whim while the `FocusLayout` is active, I get the following error during the re-start:

Whim has shut down after encountering unexpected exception:

```
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'index')
   at System.Collections.Immutable.Requires.FailRange(String parameterName, String message)
   at System.Collections.Immutable.ImmutableList`1.Node.ItemRef(Int32 index)
   at System.Collections.Immutable.ImmutableList`1.get_Item(Int32 index)
   at Whim.FocusLayoutEngine.MinimizeWindowStart(IWindow window) in C:\Users\rober\dev\Whim\src\Whim\Layout\FocusLayoutEngine.cs:line 251
   at Whim.FloatingLayout.FloatingLayoutEngine.MinimizeWindowStart(IWindow window) in C:\Users\rober\dev\Whim\src\Whim.FloatingLayout\FloatingLayoutEngine.cs:line 252
   at Whim.Bar.BarLayoutEngine.MinimizeWindowStart(IWindow window) in C:\Users\rober\dev\Whim\src\Whim.Bar\BarLayoutEngine.cs:line 77
   at Whim.Gaps.GapsLayoutEngine.MinimizeWindowStart(IWindow window) in C:\Users\rober\dev\Whim\src\Whim.Gaps\GapsLayoutEngine.cs:line 122
   at Whim.Workspace.MinimizeWindowStart(IWindow window) in C:\Users\rober\dev\Whim\src\Whim\Workspace\Workspace.cs:line 148
   at Whim.ButlerEventHandlers.WindowManager_WindowAdded(Object sender, WindowEventArgs args) in C:\Users\rober\dev\Whim\src\Whim\Butler\ButlerEventHandlers.cs:line 86
   at Whim.WindowManager.OnWindowAdded(IWindow window) in C:\Users\rober\dev\Whim\src\Whim\Window\WindowManager.cs:line 363
   at Whim.Butler.Initialize() in C:\Users\rober\dev\Whim\src\Whim\Butler\Butler.cs:line 95
   at Whim.Context.Initialize() in C:\Users\rober\dev\Whim\src\Whim\Context\Context.cs:line 104
   at Whim.Runner.App.StartWhim() in C:\Users\rober\dev\Whim\src\Whim.Runner\App.xaml.cs:line 46
```

### Additional observations

- This only occurs when using the `Restart` command. Exiting Whim and then starting manually works fine.
- This only occurs when there are at least 2 windows on the workspace where the `FocusLayout` is active. If there's just one, restarting works fine.

### Minimal config to reproduce

```csharp
#nullable enable
#r "WHIM_PATH\whim.dll"
#r "WHIM_PATH\plugins\Whim.Bar\Whim.Bar.dll"
#r "WHIM_PATH\plugins\Whim.CommandPalette\Whim.CommandPalette.dll"
#r "WHIM_PATH\plugins\Whim.FloatingLayout\Whim.FloatingLayout.dll"
#r "WHIM_PATH\plugins\Whim.FocusIndicator\Whim.FocusIndicator.dll"
#r "WHIM_PATH\plugins\Whim.Gaps\Whim.Gaps.dll"
#r "WHIM_PATH\plugins\Whim.LayoutPreview\Whim.LayoutPreview.dll"
#r "WHIM_PATH\plugins\Whim.SliceLayout\Whim.SliceLayout.dll"
#r "WHIM_PATH\plugins\Whim.TreeLayout\Whim.TreeLayout.dll"
#r "WHIM_PATH\plugins\Whim.TreeLayout.Bar\Whim.TreeLayout.Bar.dll"
#r "WHIM_PATH\plugins\Whim.TreeLayout.CommandPalette\Whim.TreeLayout.CommandPalette.dll"
#r "WHIM_PATH\plugins\Whim.Updater\Whim.Updater.dll"

using System;
using System.Collections.Generic;
using Whim;
using Whim.Bar;
using Whim.CommandPalette;
using Whim.FloatingLayout;
using Whim.FocusIndicator;
using Whim.Gaps;
using Whim.LayoutPreview;
using Whim.SliceLayout;
using Whim.TreeLayout;
using Whim.TreeLayout.Bar;
using Whim.TreeLayout.CommandPalette;
using Whim.Updater;
using Windows.Win32.UI.Input.KeyboardAndMouse;
using Microsoft.UI;
using Microsoft.UI.Xaml.Media;

void DoConfig(IContext context)
{
    context.Logger.Config = new LoggerConfig() { BaseMinLogLevel = LogLevel.Debug };

    CommandPaletteConfig commandPaletteConfig = new(context);
    CommandPalettePlugin commandPalettePlugin = new(context, commandPaletteConfig);
    context.PluginManager.AddPlugin(commandPalettePlugin);

    TreeLayoutPlugin treeLayoutPlugin = new(context);
    context.PluginManager.AddPlugin(treeLayoutPlugin);

    List<BarComponent> leftComponents = new() { ActiveLayoutWidget.CreateComponent() };
    List<BarComponent> centerComponents = new();
    List<BarComponent> rightComponents = new();

    BarConfig barConfig = new(leftComponents, centerComponents, rightComponents);
    BarPlugin barPlugin = new(context, barConfig);
    context.PluginManager.AddPlugin(barPlugin);

    context.WorkspaceManager.Add("1");
    context.WorkspaceManager.Add("2");

    context.WorkspaceManager.CreateLayoutEngines = () => new CreateLeafLayoutEngine[]
    {
        (id) => new TreeLayoutEngine(context, treeLayoutPlugin, id),
        (id) => new FocusLayoutEngine(id)
    };
}
return DoConfig;
```

### Steps to reproduce

1. Add multiple windows on workspace 1
2. Use the `ActiveLayoutWidget` on the bar to activate the `FocusLayout` on workspace 1
3. Use the command palette (`Win + Shift + K`) to restart whim

**Comment by dalyIsaac** [comment]
Sorry, this was a bit of a sloppy bug. Should be fixed now.
